services:

  backend:
    build: ./backend
    container_name: task-manager-backend
    expose:
      - "5000"

  database:
    image: postgres:17-alpine
    container_name: task-manager-database
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  


  frontend:
    build: ./frontend
    container_name: task-manager-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend 

volumes:
  postgres_data:
